server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Saari requests ko index.html par fallback kar do (React Router handles it)
        try_files $uri $uri/ /index.html; 
    }

    # Optional: static assets (js, css, images) ke liye caching
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        root /usr/share/nginx/html;
        expires 6m;
        access_log off;
    }
}