FROM node:18 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .


FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install --only=production

COPY --from=builder /app/src ./src
COPY --from=builder /app/server.js ./

EXPOSE 3000

CMD ["node", "server.js"]